### ISSUE TITLE
Help understanding KWL in automations.yaml

### ISSUE THREAD

**Issue by skl283** [moe01324/home_automation#1]
Hi Moe,

thank you for your cool HA Setup and your Inspirations!

I have some small questions to your KWL Setup and i hope you can help me to understand your Setup?! :-)

Could you explain the following Automation to me? What is exactly done/what Group-Adresses are these or why are you doing this Automation? I understand, that you set KWL to Stufe 1 at 8:00, to 2 at 17:20 and to 1 at 22:00.

in automations.yaml
```
- alias: Lüftung ausschalten
  trigger:
    at: '08:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.kwl_stufe_1
    service: switch.turn_on
## Lüftung am Nachmittag einschalten
- alias: Lüftung einschalten
  trigger:
    at: '17:20:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.kwl_stufe_2
    service: switch.turn_on
## Lüftung am Abend ausschalten    
- alias: Lüftung Abend ausschalten
  trigger:
    at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.kwl_stufe_1
    service: switch.turn_on
```
But what are you exactly doing here? what are  the group Adresses 6/7/2 and  6/7/4?

```
## KWL Modus korrekt setzen
- alias: KWL Auto
  trigger:
  - at: '10:00'
    platform: time
  condition: []
  action:
  - data:
      address: 6/7/4
      payload: '0'
    service: knx.send
  - data:
      address: 6/7/2
      payload: '0'
    service: knx.send
```
